# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tr/repos/cgab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tr/repos/cgab

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tr/repos/cgab/CMakeFiles /home/tr/repos/cgab//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tr/repos/cgab/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cgab

# Build rule for target.
cgab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cgab
.PHONY : cgab

# fast build rule for target.
cgab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/build
.PHONY : cgab/fast

#=============================================================================
# Target rules for targets named gab

# Build rule for target.
gab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gab
.PHONY : gab

# fast build rule for target.
gab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/build
.PHONY : gab/fast

src/cgab/engine.o: src/cgab/engine.c.o
.PHONY : src/cgab/engine.o

# target to build an object file
src/cgab/engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/engine.c.o
.PHONY : src/cgab/engine.c.o

src/cgab/engine.i: src/cgab/engine.c.i
.PHONY : src/cgab/engine.i

# target to preprocess a source file
src/cgab/engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/engine.c.i
.PHONY : src/cgab/engine.c.i

src/cgab/engine.s: src/cgab/engine.c.s
.PHONY : src/cgab/engine.s

# target to generate assembly for a file
src/cgab/engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/engine.c.s
.PHONY : src/cgab/engine.c.s

src/cgab/gc.o: src/cgab/gc.c.o
.PHONY : src/cgab/gc.o

# target to build an object file
src/cgab/gc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/gc.c.o
.PHONY : src/cgab/gc.c.o

src/cgab/gc.i: src/cgab/gc.c.i
.PHONY : src/cgab/gc.i

# target to preprocess a source file
src/cgab/gc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/gc.c.i
.PHONY : src/cgab/gc.c.i

src/cgab/gc.s: src/cgab/gc.c.s
.PHONY : src/cgab/gc.s

# target to generate assembly for a file
src/cgab/gc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/gc.c.s
.PHONY : src/cgab/gc.c.s

src/cgab/lexer.o: src/cgab/lexer.c.o
.PHONY : src/cgab/lexer.o

# target to build an object file
src/cgab/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/lexer.c.o
.PHONY : src/cgab/lexer.c.o

src/cgab/lexer.i: src/cgab/lexer.c.i
.PHONY : src/cgab/lexer.i

# target to preprocess a source file
src/cgab/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/lexer.c.i
.PHONY : src/cgab/lexer.c.i

src/cgab/lexer.s: src/cgab/lexer.c.s
.PHONY : src/cgab/lexer.s

# target to generate assembly for a file
src/cgab/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/lexer.c.s
.PHONY : src/cgab/lexer.c.s

src/cgab/object.o: src/cgab/object.c.o
.PHONY : src/cgab/object.o

# target to build an object file
src/cgab/object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/object.c.o
.PHONY : src/cgab/object.c.o

src/cgab/object.i: src/cgab/object.c.i
.PHONY : src/cgab/object.i

# target to preprocess a source file
src/cgab/object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/object.c.i
.PHONY : src/cgab/object.c.i

src/cgab/object.s: src/cgab/object.c.s
.PHONY : src/cgab/object.s

# target to generate assembly for a file
src/cgab/object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/object.c.s
.PHONY : src/cgab/object.c.s

src/cgab/parser.o: src/cgab/parser.c.o
.PHONY : src/cgab/parser.o

# target to build an object file
src/cgab/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/parser.c.o
.PHONY : src/cgab/parser.c.o

src/cgab/parser.i: src/cgab/parser.c.i
.PHONY : src/cgab/parser.i

# target to preprocess a source file
src/cgab/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/parser.c.i
.PHONY : src/cgab/parser.c.i

src/cgab/parser.s: src/cgab/parser.c.s
.PHONY : src/cgab/parser.s

# target to generate assembly for a file
src/cgab/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/parser.c.s
.PHONY : src/cgab/parser.c.s

src/cgab/vm.o: src/cgab/vm.c.o
.PHONY : src/cgab/vm.o

# target to build an object file
src/cgab/vm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/vm.c.o
.PHONY : src/cgab/vm.c.o

src/cgab/vm.i: src/cgab/vm.c.i
.PHONY : src/cgab/vm.i

# target to preprocess a source file
src/cgab/vm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/vm.c.i
.PHONY : src/cgab/vm.c.i

src/cgab/vm.s: src/cgab/vm.c.s
.PHONY : src/cgab/vm.s

# target to generate assembly for a file
src/cgab/vm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgab.dir/build.make CMakeFiles/cgab.dir/src/cgab/vm.c.s
.PHONY : src/cgab/vm.c.s

src/gab/main.o: src/gab/main.c.o
.PHONY : src/gab/main.o

# target to build an object file
src/gab/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/src/gab/main.c.o
.PHONY : src/gab/main.c.o

src/gab/main.i: src/gab/main.c.i
.PHONY : src/gab/main.i

# target to preprocess a source file
src/gab/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/src/gab/main.c.i
.PHONY : src/gab/main.c.i

src/gab/main.s: src/gab/main.c.s
.PHONY : src/gab/main.s

# target to generate assembly for a file
src/gab/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/src/gab/main.c.s
.PHONY : src/gab/main.c.s

src/os/os.o: src/os/os.c.o
.PHONY : src/os/os.o

# target to build an object file
src/os/os.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/src/os/os.c.o
.PHONY : src/os/os.c.o

src/os/os.i: src/os/os.c.i
.PHONY : src/os/os.i

# target to preprocess a source file
src/os/os.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/src/os/os.c.i
.PHONY : src/os/os.c.i

src/os/os.s: src/os/os.c.s
.PHONY : src/os/os.s

# target to generate assembly for a file
src/os/os.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gab.dir/build.make CMakeFiles/gab.dir/src/os/os.c.s
.PHONY : src/os/os.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cgab"
	@echo "... gab"
	@echo "... src/cgab/engine.o"
	@echo "... src/cgab/engine.i"
	@echo "... src/cgab/engine.s"
	@echo "... src/cgab/gc.o"
	@echo "... src/cgab/gc.i"
	@echo "... src/cgab/gc.s"
	@echo "... src/cgab/lexer.o"
	@echo "... src/cgab/lexer.i"
	@echo "... src/cgab/lexer.s"
	@echo "... src/cgab/object.o"
	@echo "... src/cgab/object.i"
	@echo "... src/cgab/object.s"
	@echo "... src/cgab/parser.o"
	@echo "... src/cgab/parser.i"
	@echo "... src/cgab/parser.s"
	@echo "... src/cgab/vm.o"
	@echo "... src/cgab/vm.i"
	@echo "... src/cgab/vm.s"
	@echo "... src/gab/main.o"
	@echo "... src/gab/main.i"
	@echo "... src/gab/main.s"
	@echo "... src/os/os.o"
	@echo "... src/os/os.i"
	@echo "... src/os/os.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

