# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Release cross-compiled static binaries

on:
  push:
    branches: [ "main" ]

env:
  x86LM: x86_64-linux-musl
  x86WG: x86_64-windows-gnu
  x86MN: x86_64-macos-none
  aarchLM: aarch64-linux-musl
  aarchWG: aarch64-windows-gnu
  aarchMN: aarch64-macos-none
  TARGETS: "$x86LM $x86WG $x86MN $aarchLM $aarchWG $aarchMN"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Clide
      run: go install github.com/TeddyRandby/clide@latest

    - name: Configure
      run: clide configure -b=release -t="$TARGETS"

    - name: Build
      run: clide build

    - name: Release
      uses: actions/upload-artifact@v4
      with:
        name: "gab-$x86LM"
        path: "build-$x86LM/gab"
