name: Release static binaries

on:
  push:
    branches: [ "main" ]

env:
  version: 0.0.1
  GH_TOKEN: ${{ github.token }}

jobs:
  build_artifacts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-linux-gnu
          - x86_64-windows-gnu
          - x86_64-macos-none
          - aarch64-linux-gnu
          - aarch64-windows-gnu
          - aarch64-macos-none
        build_type:
          - release
          - debug

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

      # Zig is the C compiler used by the build system
    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

      # Build system depends on Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

      # Build system tool
    - name: Install Clide
      run: go install github.com/TeddyRandby/clide@latest

    - name: Configure
      run: clide configure -b='${{ matrix.build_type }}' -t='${{ matrix.target }}'

    - name: Build
      run: clide build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}'
        path: 'build-${{ matrix.target }}/gab'

  run_tests:
    strategy:
      matrix:
        build_type:
          - release
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            target: x86_64-linux-gnu
          - os: windows-latest
            target: x86_64-windows-gnu
          - os: macos-latest
            target: x86_64-macos-none

    runs-on: ${{ matrix.os }}
    needs: build_artifacts

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}'

      - name: Run tests
        run: gab run test

  create_release:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      # Using the github cli, create a new release for this version's tag. (If it doesnt' exist)
      - name: Create Release If Not Exists
        run:  git tag | grep '${{ env.version }}' || gh release create -R '${{ github.repository }}' '${{ env.version }}' --generate-notes

  release_artifacts:
    runs-on: ubuntu-latest
    needs: create_release

    strategy:
      matrix:
        target:
          - x86_64-linux-gnu
          - x86_64-windows-gnu
          - x86_64-macos-none
          - aarch64-linux-gnu
          - aarch64-windows-gnu
          - aarch64-macos-none
        build_type:
          - release
          - debug

    steps:
      # Download artifacts created by the build step
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}'

      - name: Rename artifact
        run: mv gab 'gab-${{ matrix.build_type }}-${{ matrix.target }}'

      # Attach these binaries to the release
      - name: Attach artifact to release
        run: gh release upload -R '${{ github.repository }}' '${{ env.version }}' 'gab-${{ matrix.build_type }}-${{ matrix.target }}'
