# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Release static binaries

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-linux-musl
          - x86_64-windows-gnu
          - x86_64-macos-none
          - aarch64-linux-musl
          - aarch64-windows-gnu
          - aarch64-macos-none

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Clide
      run: go install github.com/TeddyRandby/clide@latest

    - name: Configure
      run: clide configure -b=release -t='${{ matrix.target }}'

    - name: Build
      run: clide build

    - name: Release
      uses: actions/upload-artifact@v4
      with:
        name: 'gab-${{ matrix.target }}'
        path: 'build-${{ matrix.target }}/gab'
