name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run:  'buildtype=debug gabprefix="$HOME" CLIDE_PATH=".clide" .clide/{buildType}/[Gabprefix]/[Installprefix]/configure.sh'
    - name: 'make & test'
      run: make test
